version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: leave_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: new_employee_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5102:5432"

  backend:
    build: ./Backend
    container_name: leave_backend
    depends_on:
      - postgres
    ports:
      - "3102:3102"
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_NAME: new_employee_db
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./Backend:/app

  frontend:
    build: ./Fronted
    container_name: leave_frontend
    ports:
      - "8172:80"
    depends_on:
      - backend
    volumes:
      - ./Fronted:/usr/share/nginx/html

  hr:
    build: ./HR_Page
    container_name: leave_hrpage
    ports:
      - "8173:80"
    depends_on:
      - backend
    volumes:
      - ./HR_Page:/usr/share/nginx/html

volumes:
  pgdata:

